syntax = "proto3";

package user;

service UsersService {
  rpc getUserByEmail (GetUserByEmailRequest) returns (User);
  rpc checkPassword(dataCheckPassword) returns (comparePassword);
  rpc changePassword(dataChangePassword) returns (changePasswordResponse);
}


message GetUserByEmailRequest {
  string email = 1;
}

message dataCheckPassword{
  string password = 1;
  string email= 2;
}

message dataChangePassword{
  string _id = 1;
  string oldPassword = 2;
  string newPassword = 3;
}

// Expected response

message User {
  string id = 1;
  string email = 2;
  string username = 3;
  string role = 4;
}

message comparePassword{
  bool check = 1;
}

message changePasswordResponse{
  string result=1;
}

